spring:
  application:
    name: mybooking-gateway
  main:
    web-application-type: reactive
  webflux:
    base-path: /mybooking/gateway
server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/mybooking/cloud-discovery/eureka
  instance:
    health-check-url-path: /actuator/health