spring:
  application:
    name: mybooking-gateway
  main:
    web-application-type: reactive
  webflux:
    base-path: /mybooking/gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8765
  servlet:
    context-path: /mybooking/iam-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/mybooking/cloud-discovery/eureka
  instance:
    health-check-url-path: /actuator/health